name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.15.1]
    steps:
      - name: Setup
        uses: pnpm/action-setup@v4
        with:
          version: 9.4.0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install

      - name: Run type check
        run: pnpm run typecheck

      - name: Run ESLint
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test
